config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  root 'welcome#index'
  get 'welcome/index'

  devise_for :users,
             :controllers => {
               :omniauth_callbacks => 'users/omniauth_callbacks',
               :registrations => 'users/registrations'
             }
  resources :users

  namespace :references do
    concern :pictureable do
      resources :pictures, only: [:index, :show, :create, :destroy]
    end
    resources :equipments
    resources :muscles, concerns: :pictureable
    resources :exercises
    resources :body_parts
  end

  resources :pictures, only: [:index, :create, :update, :destroy]

  namespace :journal do
    resources :items
  end

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  devise :omniauthable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  validates :email, length: { maximum: 100 }

  #callbacks

  before_save {
    self.email = email.downcase if email
  }

  after_create :create_profile

  # associations

  has_many :identities, :dependent => :delete_all
  has_one  :journal, dependent: :destroy
  has_one  :profile, dependent: :destroy

  #methods
  
  # создаем журнал, если не создан
  alias :original_journal_method :journal
  def journal
    if original_journal_method.nil? 
      Rails.logger.warn "Create journal for user_id #{self.id}"
      Journal.create(user: self)
    else
      original_journal_method
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if (data = session["devise.auth_data"])
        data = Utils::OAuth.normalize data
        user.email = data.info.email if user.email.blank?
      end
    end
  end

  def self.find_for_oauth(normalized_auth, signed_in_user = nil)
    identity = Identity.find_for_oauth normalized_auth
    user = identity.user || signed_in_user || User.find_by_email(identity.email)

    if user.nil?
      generated_password = Devise.friendly_token.first(8)
      user = User.new(
          email: identity.email,
          confirmed_at: DateTime.now,
          password: generated_password,
          password_confirmation: generated_password
      )
      user.skip_confirmation!
      user.save!
      user.profile.update_attributes(
        first_name: normalized_auth.info.first_name,
        last_name: normalized_auth.info.last_name 
      )
      UserMailer.delay.welcome(user.id, generated_password) if user.persisted?
    end

    if user.persisted? && identity.user != user
      identity.user = user
      identity.save!
    end

    user
  end

  private

  def create_profile
    Profile.create(user: self) unless profile
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def vkontakte
    generic_callback 'vkontakte'
  end

  def google_oauth2
    generic_callback 'google_oauth2'
  end

  def generic_callback( provider )
    @user = User.find_for_oauth(Utils::OAuth.normalize(env['omniauth.auth']), current_user)

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: provider.capitalize) if is_navigational_format?
    else
      session['devise.auth_data'] = env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def birthday(user)
    if user.date_of_birth
      user.date_of_birth.strftime("%d.%m.%Y")
    else
      ''
    end
  end
end

app/views/users/shared/_links.html.haml
%div.login

  - if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
    = link_to t('.forgot'), new_password_path(resource_name)
    %br

  - if devise_mapping.confirmable? && controller_name != 'confirmations'
    = link_to t('.reconfirmation'), new_confirmation_path(resource_name)
    %br

  - if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
    = link_to t('.unlock'), new_unlock_path(resource_name)
    %br

  - if devise_mapping.omniauthable? && %w(registrations sessions).include?(controller_name)
    %div.socialButtons.row
      - resource_class.omniauth_providers.each do |provider|
        %div.col-xs-4.col-sm-4.colSocial
          = link_to omniauth_authorize_path(resource_name, provider), class: "btn btn-block btn-#{auth_provider_to_css(provider)}" do
            %i.fa.fa-2x{class: "fa-#{auth_provider_to_css(provider)}"}
            %span.hidden-xs