config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  root 'welcome#index'
  get 'welcome/index'

  devise_for :users,
             :controllers => {
               :omniauth_callbacks => 'users/omniauth_callbacks',
               :registrations => 'users/registrations'
             }
  resources :users

  namespace :references do
    concern :pictureable do
      resources :pictures, only: [:index, :show, :create, :destroy]
    end
    resources :equipments
    resources :muscles, concerns: :pictureable
    resources :exercises
    resources :body_parts
  end

  resources :pictures, only: [:index, :create, :update, :destroy]

  namespace :journal do
    resources :items
  end

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/references.rb
module References
  def self.table_name_prefix
    'references_'
  end
end

app/models/references/body_part.rb
class References::BodyPart < ActiveRecord::Base
  include Anatomic

  has_and_belongs_to_many :muscles
  has_and_belongs_to_many :exercises

  scope :with_muscles, -> {
    includes(:muscles).where.not(references_muscles: { id: nil })
  }
end

app/models/references/equipment.rb
class References::Equipment < ActiveRecord::Base
  include Anatomic
end

app/models/references/equipment_join.rb
class References::EquipmentJoin < ActiveRecord::Base
  self.primary_keys = :equipmentable_id, :equipmentable_type, :equipment_id

  belongs_to :equipment, :class_name => 'References::Equipment'
  belongs_to :equipmentable, polymorphic: true

  validates_uniqueness_of :equipment_id, scope: [:equipmentable_id, :equipmentable_type]
end

app/models/references/exercise.rb
class References::Exercise < ActiveRecord::Base
  include Anatomic

  has_and_belongs_to_many :body_parts
  has_and_belongs_to_many :muscles

  has_many :equipment_joins, :class_name => 'References::EquipmentJoin', as: :equipmentable
  has_many :equipments, :class_name => 'References::Equipment', through: :equipment_joins
end

app/models/references/muscle.rb
class References::Muscle < ActiveRecord::Base
  include Anatomic

  has_and_belongs_to_many :body_parts
  has_and_belongs_to_many :exercises

  serialize :shape, Muscles::Shape
  validates_inclusion_of :shape, in: Muscles::Shape.values

  scope :no_bodypart, -> {
      where('id NOT IN (SELECT DISTINCT(muscle_id) FROM references_body_parts_muscles)')
  }

  has_many :picture_links, as: :pictureable, dependent: :destroy
  has_many :pictures, through: :picture_links
end

app/controllers/references/body_parts_controller.rb
class References::BodyPartsController < AnatomicController

  def index
    @body_parts = References::BodyPart.all.eager_load(:exercises, :muscles)
    respond_with @body_parts,
                 each_serializer: request.format == :json && params[:short] ?
                     References::BodyPartShortSerializer :
                     References::BodyPartSerializer
  end

  private

  def resource_params
    accessible = [ :name, :alias, :description, :shape, :muscle_ids => [], :exercise_ids  => [] ]
    params.require(:body_part).permit(accessible)
  end
end

app/controllers/references/equipments_controller.rb
class References::EquipmentsController < ApplicationController
  respond_to :json, only: [:index]

  def index
    @equipments = References::Equipment.all
    respond_with @equipments
  end
end

app/controllers/references/exercises_controller.rb
class References::ExercisesController < AnatomicController

  def index
    @exercises = References::Exercise.all.eager_load(:equipments, :body_parts, :muscles)
    respond_with @exercises,
                 each_serializer: request.format == :json && params[:short] ?
                     References::ExerciseShortSerializer :
                     References::ExerciseSerializer
  end

  private

  def resource_params
    accessible = [ :name, :alias, :description, :body_part_ids => [], :muscle_ids  => [], :equipment_ids  => [] ]
    params.require(:exercise).permit(accessible)
  end
end

app/controllers/references/muscles_controller.rb
class References::MusclesController < AnatomicController
  def index
    @body_parts = References::BodyPart.with_muscles.order(:name)
    @muscles = References::Muscle.no_bodypart
    respond_with References::Muscle.all
  end

  private

  def resource_params
    accessible = [ :name, :alias, :description, :shape, :body_part_ids => [], :exercise_ids  => [], :pictures_attributes => [] ]
    params.require(:muscle).permit(accessible)
  end
end

app/controllers/references/pictures_controller.rb
class References::PicturesController < ApplicationController
  respond_to :html, only: [:index]
  respond_to :json

  before_action :authenticate_user!
  authorize_resource
  before_action :load_parent, only: [:index, :show, :create, :destroy]

  def index
    @pictures = @parent.pictures.all
    respond_with @pictures
  end

  def show
    @picture = @parent.pictures.find(params[:id])
    respond_with @picture
  end

  def create
    @picture = Picture.find(params[:l_id])
    @parent.pictures << @picture
    respond_with @picture
  end

  def destroy
    @picture = Picture.find(params[:id])
    @picture = @parent.pictures.delete(@picture)
    respond_with @picture
  end

  private

  def load_parent
    parent_klasses = %w[muscle]
    if klass = parent_klasses.detect { |pk| params[:"#{pk}_id"].present? }
      @parent = "References::#{klass.camelize}".constantize.find params[:"#{klass}_id"]
    end
  end
end

app/views/references/muscles/_form.html.haml
- model_name = 'muscle'
= form_for(@muscle, as: model_name, html: {class: 'form-horizontal', data: {model: model_name}}) do |f|
  .form-group
    = f.label :name, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :name, class: 'form-control'
      %span.help-block

  .form-group
    = f.label :alias, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :alias, class: 'form-control'
      %span.help-block

  .form-group
    = f.label :shape, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.collection_select :shape, Muscles::Shape.values, :value, :human_name, {}, {class: 'form-control'}
      %span.help-block

  .form-group
    = f.label :description, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_area :description, {class: 'form-control'}
      %span.help-block

  .form-group
    = f.label :body_parts, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.collection_select(:body_part_ids, References::BodyPart.all, :id, :name, {:selected => f.object.body_part_ids}, {id:"#{model_name}_body_parts", class:'multi form-control', :multiple => true})
      %span.help-block

  .form-group
    = f.label :exercises, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.collection_select(:exercise_ids, References::Exercise.all, :id, :name, {:selected => f.object.exercise_ids}, {id:"#{model_name}_exercises", class:'multi form-control', :multiple => true})
      %span.help-block

  .form-group
    %div.col-sm-offset-5.col-sm-4.col-md-offset-5.col-md-4
      = button_tag(type: 'submit', class: "btn-block btn btn btn-success") do
        %i.fa.fa-check
        = t '.actions.save'

:coffeescript
  $ ->
    $('select.multi').multiselect(
      enableFiltering: true,
      enableCaseInsensitiveFiltering: true,
      filterBehavior: 'both',
      buttonContainer: '<div class="btn-group" />',
      buttonWidth: '100%',
      templates:
        button: '<button type="button" class="multiselect dropdown-toggle" data-toggle="dropdown"><span class="multiselect-selected-text"></span> <b class="caret"></b></button>',
        ul: '<ul class="multiselect-container dropdown-menu"></ul>',
        filter: '<li class="multiselect-item filter"><div class="input-group"><span class="input-group-addon"><i class="fa fa-search"></i></span><input class="form-control multiselect-search" type="text"></div></li>',
        filterClearBtn: '<span class="input-group-btn"><button class="btn btn-default multiselect-clear-filter" type="button"><i class="fa fa-times-circle"></i></button></span>',
        li: '<li><a tabindex="0"><label></label></a></li>',
        divider: '<li class="multiselect-item divider"></li>',
        liGroup: '<li class="multiselect-item multiselect-group"><label></label></li>'
    )

    unsaved = false

    $('button[type=\'submit\']').click ->
      unsaved = false
      return true

    $('#content').on 'change', ':input', ->
      unsaved = true

    $(window).bind 'beforeunload', ->
      if unsaved
        return "#{t 'unsaved_alert'}"

- if @muscle.errors.any?
  :coffeescript
    $ ->
      $("form[data-model=muscle]").renderFormErrors(#{@muscle.errors.to_json.html_safe})

app/views/references/muscles/edit.html.haml
%h3 #{t '.title'}

= render partial: 'form'

app/views/references/muscles/index.html.haml
%h3 #{References::Muscle.model_name.human(count: '')}

#muscles-by-bodyparts
  %div.list-group#bodyparts
    - @body_parts.each do |body_part|
      %a.list-group-item{href: "#"+body_part.alias, data: {toggle: "collapse", parent:"#bodyparts"}}
        %strong
          #{body_part.name}
          %span.badge.badge-info #{body_part.muscles.size}
      %div.collapse{id: body_part.alias}
        - body_part.muscles.each do |muscle|
          = link_to muscle.name, muscle, class: "list-group-item sublevel", data: {parent: '#'+body_part.alias}

    - if @muscles.size > 0
      %a.list-group-item{href: "#others", data: {toggle: "collapse", parent:"#others"}}
        %strong
          = t '.no_group'
          %span.badge.badge-info #{@muscles.size}
      %div.collapse{id: 'others'}
        - @muscles.each do |muscle|
          = link_to muscle.name, muscle, class: "list-group-item sublevel", data: {parent: '#others'}

- if can? :manage, References::Muscle
  .row
    .col-sm-4.col-sm-offset-4
      .btn-group-justified
        = link_to t('.actions.new'), new_references_muscle_path, class: 'btn btn-primary'

app/views/references/muscles/new.html.haml
%h3 #{t '.title'}

= render partial: 'form'

app/views/references/muscles/show.html.haml
%h3
  - if can? :manage, @muscle
    .dropdown.pull-right
      %a.btn.btn-sm.btn-primary.dropdown-toggle#dropdownMenu1{type: "button", data:{toggle:"dropdown"}, aria:{haspopup:"true", expanded:"false"}}
        %i.fa.fa-cog
        %span.caret
      %ul.dropdown-menu{aria:{labelledby:"dropdownMenu1"}}
        %li
          = link_to edit_references_muscle_path(@muscle) do
            %i.fa.fa-edit
            = t '.actions.edit'
        %li
          = link_to references_muscle_pictures_path(@muscle) do
            %i.fa.fa-file-image-o
            = t '.actions.pictures_manage'
        %li
          = link_to '#', data: { toggle: "modal", target: "#confirm-delete"} do
            %i.fa.fa-trash-o
            = t '.actions.delete'

  %div{style: 'margin-right: 50px;  overflow: hidden; text-overflow: ellipsis; white-space: nowrap;'}
    = link_to References::Muscle.model_name.human(count: ''), references_muscles_path
    %i.fa.fa-chevron-right{style: 'font-size: 0.8em;'}
    #{@muscle.name}

.row
  .col-lg-12
    .right-floated-box
      %ul.list-group
        %li.list-group-item.text-center.active
          %strong
            = @muscle.alias.humanize
        %li.list-group-item
          %strong #{References::Muscle.human_attribute_name 'shape'}:
          = @muscle.shape.human_name
        %li.list-group-item
          %strong #{References::Muscle.human_attribute_name 'body_parts'}:
          = @muscle.body_parts.map{ |b| link_to(b.name, b) }.join(', ').html_safe
        %li.list-group-item
          %strong #{References::Muscle.human_attribute_name 'exercises'}:
          = @muscle.exercises.map{ |e| link_to(e.name, e) }.join(', ').html_safe

    = markdown(@muscle.description)

.panel-group
  .panel.panel-default
    .panel-heading
      %h4.panel-title
        %strong #{References::Muscle.human_attribute_name 'pictures'}
        [
        %a{href: "#images", data: { toggle: "collapse"} } +
        ]
    #images.panel-collapse.collapse
      .panel-body
        .row
          - @muscle.pictures.each do |p|
            .col-xs-6.col-sm-6.col-md-3
              .thumbnail
                = link_to p.image_url, rel: 'lightbox', data: {lightbox: 'anatomy', title: p.name} do
                  = image_tag p.image_url(:small)
                .caption
                  %strong #{p.name}

.modal.fade#confirm-delete{tabindex:"-1", role: "dialog", aria: {labelledby: "myModalLabel", hidden: "true"}}
  .modal-dialog
    .modal-content
      .modal-header
        %button{type: "button", class: "close", data: {dismiss: "modal"}, aria: {hidden: "true"}} &times;
        %h4.modal-title#myModalLabel #{t '.modal_delete.title'}
      .modal-body
        #{t '.modal_delete.body'}
      .modal-footer
        %button{type: "button", class: "btn btn-default", data: {dismiss: "modal"}} #{t '.modal_delete.cancel'}
        = link_to @muscle, class: "btn btn-danger btn-ok", method: 'delete' do
          %i.fa.fa-trash-o
          = t '.actions.delete'