config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  root 'welcome#index'
  get 'welcome/index'

  devise_for :users,
             :controllers => {
               :omniauth_callbacks => 'users/omniauth_callbacks',
               :registrations => 'users/registrations'
             }
  resources :users

  namespace :references do
    concern :pictureable do
      resources :pictures, only: [:index, :show, :create, :destroy]
    end
    resources :equipments
    resources :muscles, concerns: :pictureable
    resources :exercises
    resources :body_parts
  end

  resources :pictures, only: [:index, :create, :update, :destroy]

  namespace :journal do
    resources :items
  end

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/references.rb
module References
  def self.table_name_prefix
    'references_'
  end
end

app/models/references/body_part.rb
class References::BodyPart < ActiveRecord::Base
  include Anatomic

  has_and_belongs_to_many :muscles
  has_and_belongs_to_many :exercises

  scope :with_muscles, -> {
    includes(:muscles).where.not(references_muscles: { id: nil })
  }
end

app/models/references/equipment.rb
class References::Equipment < ActiveRecord::Base
  include Anatomic
end

app/models/references/equipment_join.rb
class References::EquipmentJoin < ActiveRecord::Base
  self.primary_keys = :equipmentable_id, :equipmentable_type, :equipment_id

  belongs_to :equipment, :class_name => 'References::Equipment'
  belongs_to :equipmentable, polymorphic: true

  validates_uniqueness_of :equipment_id, scope: [:equipmentable_id, :equipmentable_type]
end

app/models/references/exercise.rb
class References::Exercise < ActiveRecord::Base
  include Anatomic

  has_and_belongs_to_many :body_parts
  has_and_belongs_to_many :muscles

  has_many :equipment_joins, :class_name => 'References::EquipmentJoin', as: :equipmentable
  has_many :equipments, :class_name => 'References::Equipment', through: :equipment_joins
end

app/models/references/muscle.rb
class References::Muscle < ActiveRecord::Base
  include Anatomic

  has_and_belongs_to_many :body_parts
  has_and_belongs_to_many :exercises

  serialize :shape, Muscles::Shape
  validates_inclusion_of :shape, in: Muscles::Shape.values

  scope :no_bodypart, -> {
      where('id NOT IN (SELECT DISTINCT(muscle_id) FROM references_body_parts_muscles)')
  }

  has_many :picture_links, as: :pictureable, dependent: :destroy
  has_many :pictures, through: :picture_links
end

app/controllers/references/body_parts_controller.rb
class References::BodyPartsController < AnatomicController

  def index
    @body_parts = References::BodyPart.all.eager_load(:exercises, :muscles)
    respond_with @body_parts,
                 each_serializer: request.format == :json && params[:short] ?
                     References::BodyPartShortSerializer :
                     References::BodyPartSerializer
  end

  private

  def resource_params
    accessible = [ :name, :alias, :description, :shape, :muscle_ids => [], :exercise_ids  => [] ]
    params.require(:body_part).permit(accessible)
  end
end

app/controllers/references/equipments_controller.rb
class References::EquipmentsController < ApplicationController
  respond_to :json, only: [:index]

  def index
    @equipments = References::Equipment.all
    respond_with @equipments
  end
end

app/controllers/references/exercises_controller.rb
class References::ExercisesController < AnatomicController

  def index
    @exercises = References::Exercise.all.eager_load(:equipments, :body_parts, :muscles)
    respond_with @exercises,
                 each_serializer: request.format == :json && params[:short] ?
                     References::ExerciseShortSerializer :
                     References::ExerciseSerializer
  end

  private

  def resource_params
    accessible = [ :name, :alias, :description, :body_part_ids => [], :muscle_ids  => [], :equipment_ids  => [] ]
    params.require(:exercise).permit(accessible)
  end
end

app/controllers/references/muscles_controller.rb
class References::MusclesController < AnatomicController
  def index
    @body_parts = References::BodyPart.with_muscles.order(:name)
    @muscles = References::Muscle.no_bodypart
    respond_with References::Muscle.all
  end

  private

  def resource_params
    accessible = [ :name, :alias, :description, :shape, :body_part_ids => [], :exercise_ids  => [], :pictures_attributes => [] ]
    params.require(:muscle).permit(accessible)
  end
end

app/controllers/references/pictures_controller.rb
class References::PicturesController < ApplicationController
  respond_to :html, only: [:index]
  respond_to :json

  before_action :authenticate_user!
  authorize_resource
  before_action :load_parent, only: [:index, :show, :create, :destroy]

  def index
    @pictures = @parent.pictures.all
    respond_with @pictures
  end

  def show
    @picture = @parent.pictures.find(params[:id])
    respond_with @picture
  end

  def create
    @picture = Picture.find(params[:l_id])
    @parent.pictures << @picture
    respond_with @picture
  end

  def destroy
    @picture = Picture.find(params[:id])
    @picture = @parent.pictures.delete(@picture)
    respond_with @picture
  end

  private

  def load_parent
    parent_klasses = %w[muscle]
    if klass = parent_klasses.detect { |pk| params[:"#{pk}_id"].present? }
      @parent = "References::#{klass.camelize}".constantize.find params[:"#{klass}_id"]
    end
  end
end

app/views/references/body_parts/_form.html.haml
- model_name = 'body_part'
= form_for(@body_part, as: model_name, html: {class: 'form-horizontal', data: {model: model_name}}) do |f|
  .form-group
    = f.label :name, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :name, class: 'form-control'
      %span.help-block

  .form-group
    = f.label :alias, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :alias, class: 'form-control'
      %span.help-block

  .form-group
    = f.label :description, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_area :description, {class: 'form-control'}
      %span.help-block

  .form-group
    = f.label :exercises, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.collection_select(:exercise_ids, References::Exercise.all, :id, :name, {:selected => f.object.exercise_ids}, {id:"#{model_name}_exercises", class:'multi form-control', :multiple => true})
      %span.help-block

  .form-group
    = f.label :muscles, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.collection_select(:muscle_ids, References::Muscle.all, :id, :name, {:selected => f.object.muscle_ids}, {id:"#{model_name}_muscles", class:'multi form-control', :multiple => true})
      %span.help-block

  .form-group
    %div.col-sm-offset-5.col-sm-4.col-md-offset-5.col-md-4
      = button_tag(type: 'submit', class: "btn-block btn btn btn-success") do
        %i.fa.fa-check
        = t '.actions.save'

:coffeescript
  $ ->
    $('select.multi').multiselect(
      enableFiltering: true,
      enableCaseInsensitiveFiltering: true,
      filterBehavior: 'both',
      buttonContainer: '<div class="btn-group" />',
      buttonWidth: '100%',
      templates:
        button: '<button type="button" class="multiselect dropdown-toggle" data-toggle="dropdown"><span class="multiselect-selected-text"></span> <b class="caret"></b></button>',
        ul: '<ul class="multiselect-container dropdown-menu"></ul>',
        filter: '<li class="multiselect-item filter"><div class="input-group"><span class="input-group-addon"><i class="fa fa-search"></i></span><input class="form-control multiselect-search" type="text"></div></li>',
        filterClearBtn: '<span class="input-group-btn"><button class="btn btn-default multiselect-clear-filter" type="button"><i class="fa fa-times-circle"></i></button></span>',
        li: '<li><a tabindex="0"><label></label></a></li>',
        divider: '<li class="multiselect-item divider"></li>',
        liGroup: '<li class="multiselect-item multiselect-group"><label></label></li>'
    );

- if @body_part.errors.any?
  :coffeescript
    $ ->
      $("form[data-model=body_part]").renderFormErrors(#{@body_part.errors.to_json.html_safe});

app/views/references/body_parts/edit.html.haml
%h3 #{t '.title'}

= render partial: 'form'

app/views/references/body_parts/index.html.haml
%h3 #{References::BodyPart.model_name.human(count: '')}
%ul
- @body_parts.each do |body_part|
  %li #{link_to body_part.name, body_part}

- if can? :manage, References::BodyPart
  .row
    .col-sm-4.col-sm-offset-4
      .btn-group-justified
        = link_to t('.actions.new'), new_references_body_part_path, class: 'btn btn-primary'

app/views/references/body_parts/new.html.haml
%h3 #{t '.title'}

= render partial: 'form'

app/views/references/body_parts/show.html.haml
%h3
  = link_to References::BodyPart.model_name.human(count: ''), references_body_parts_path
  \\
  #{@body_part.name}

  - if can? :manage, @body_part
    .dropdown.pull-right
      %a.btn.btn-sm.btn-primary.dropdown-toggle#dropdownMenu1{type: "button", data:{toggle:"dropdown"}, aria:{haspopup:"true", expanded:"false"}}
        %i.fa.fa-cog
        %span.caret
      %ul.dropdown-menu{aria:{labelledby:"dropdownMenu1"}}
        %li
          = link_to edit_references_body_part_path(@body_part) do
            %i.fa.fa-edit
            = t '.actions.edit'
        %li
          = link_to '#', data: { toggle: "modal", target: "#confirm-delete"} do
            %i.fa.fa-trash-o
            = t '.actions.delete'

%strong #{References::BodyPart.human_attribute_name 'alias'}:
= @body_part.alias.humanize

%br

%strong #{References::BodyPart.human_attribute_name 'exercises'}:
= @body_part.exercises.map{ |e| link_to(e.name, e) }.join(', ').html_safe

%br

%strong #{References::BodyPart.human_attribute_name 'muscles'}:
= @body_part.muscles.map{ |m| link_to(m.name, m) }.join(', ').html_safe

%br

%strong #{References::BodyPart.human_attribute_name 'description'}:
%br
= @body_part.description

.modal.fade#confirm-delete{tabindex:"-1", role: "dialog", aria: {labelledby: "myModalLabel", hidden: "true"}}
  .modal-dialog
    .modal-content
      .modal-header
        %button{type: "button", class: "close", data: {dismiss: "modal"}, aria: {hidden: "true"}} &times;
        %h4.modal-title#myModalLabel #{t '.modal_delete.title'}
      .modal-body
        = t '.modal_delete.body'
      .modal-footer
        %button{type: "button", class: "btn btn-default", data: {dismiss: "modal"}} #{t '.modal_delete.cancel'}
        = link_to @body_part, class: "btn btn-danger btn-ok", method: 'delete' do
          %i.fa.fa-trash-o
          = t '.actions.delete'