config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  root 'welcome#index'
  get 'welcome/index'

  devise_for :users,
             :controllers => {
               :omniauth_callbacks => 'users/omniauth_callbacks',
               :registrations => 'users/registrations'
             }
  resources :users

  namespace :references do
    concern :pictureable do
      resources :pictures, only: [:index, :show, :create, :destroy]
    end
    resources :equipments
    resources :muscles, concerns: :pictureable
    resources :exercises
    resources :body_parts
  end

  resources :pictures, only: [:index, :create, :update, :destroy]

  namespace :journal do
    resources :items
  end

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/views/layouts/_footer.ru.haml
%p
  &copy;
  %a{href: 'mailto:davydes@gmail.com'} Давыдов Евгений 2016

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default{role: "navigation"}
  .navbar-header
    %button.navbar-toggle{data:{target: '.sidebar-nav', toggle: 'offcanvas'}, type: "button"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand{href: root_path}
      Gym
      #{'<sup><strong class="alert-info">dev</strong></sup>'.html_safe if Rails.env.development?}
      #{'<sup><strong class="alert-info">staging</strong></sup>'.html_safe if Rails.env.staging?}
      #{'<sup><strong class="alert-danger">admin</strong></sup>'.html_safe if admin?}
  .collapse.navbar-collapse
    %ul.nav.navbar-nav.navbar-right
      %li
        - if !current_user
          = link_to new_user_session_path do
            = t 'sessions.sign_in'
            %i.fa.fa-sign-in
        - else
          = link_to destroy_user_session_path, :method => :delete do
            = t 'sessions.sign_out'
            %i.fa.fa-sign-out

app/views/layouts/_menu.html.haml
%ul.nav.nav-pills.nav-stacked
  = menu_link_to references_muscles_path do
    %i.fa.fa-fw.fa-book
    = References::Muscle.model_name.human(count: '')
    - cache 'muscles_count', :expires_in => 5.minutes do
      %span.badge.badge-info #{References::Muscle.count}
  = menu_link_to references_exercises_path do
    %i.fa.fa-fw.fa-book
    = References::Exercise.model_name.human(count: '')
    - cache 'exercises_count', :expires_in => 5.minutes do
      %span.badge.badge-info #{References::Exercise.count}

  - if current_user
    = menu_link_to journal_items_path do
      %i.fa.fa-fw.fa-book
      = Journal.model_name.human
    = menu_link_to users_path do
      %i.fa.fa-fw.fa-user
      = t 'users.members'
      - cache 'users_count', :expires_in => 5.minutes do
        %span.badge.badge-info #{User.count}
    = menu_link_to edit_user_registration_path do
      %i.fa.fa-fw.fa-briefcase
      = t 'users.profile'
    = menu_link_to destroy_user_session_path, :method => :delete do
      %i.fa.fa-fw.fa-sign-out
      = t 'sessions.sign_out'
  - else
    = menu_link_to new_user_session_path do
      %i.fa.fa-sign-in
      = t 'sessions.sign_in'

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %title= page_title
    %meta{name:"viewport", content:"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"}
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    = favicon_link_tag 'g.ico'

    :coffeescript
      $ ->
        I18n.defaultLocale = "#{I18n.default_locale}"
        I18n.locale = "#{I18n.locale}"

  %body
    #page-wrap
      .container
        = render partial: 'layouts/header'
      .container
        .row.row-offcanvas.row-offcanvas-left
          .col-xs-6.col-md-3.col-sm-4.sidebar-offcanvas#sidebar{role:"navigation"}
            = render partial: 'layouts/menu'
          .col-xs-12.col-md-9.col-sm-8#content
            - if notice
              .alert.alert-info.alert-3s{:role => "alert"}= notice
            - if alert
              .alert.alert-danger.alert-3s{:role => "alert"}= alert
            = yield
      #page-push
    #page-footer
      .container
        = render partial: 'layouts/footer'